### ISSUE TITLE
Route `/bot/channel/detail/:id/alias/list` ending in status 500

### ISSUE THREAD

**Issue by EuleHaken** [Supinic/supinic.com#35]
When you visit the endpoint [`/bot/channel/detail/:id/alias/list`](https://supinic.com/bot/channel/detail/:id/alias/list) and the provided `:id` (the provided channel) was not found, the api, that the endpoint calls, returns with `data: null`. However, in [`channel.js` at line 169](https://github.com/Supinic/supinic.com/blob/master/routes/bot/channel.js#L169), we expect, that `response.body.data` is never null. But because it is null, the endpoint gives us a 500. (See error ID:  53550 for example)

I wasn't sure whether you want to just check for that case, when `data` is null, or rather change the [api endpoint](https://github.com/Supinic/supinic.com/blob/master/routes/api/bot/channel.js#L157) to return an empty array, if the channel was not found. That's why I didn't make any PR, so I'll leave the rest for you😃

**Comment by Supinic** [comment]
Fixed in c2484882ee15e4d2b911bb395ecf567903bf9ad3
