### ISSUE TITLE
S#5386 - Add song names to page title

### ISSUE THREAD

**Issue by Supinic** [Supinic/supinic.com#8]
[S#5386](https://supinic.com/data/suggestion/5386) by *supinic*

In the Track detail [route](https://github.com/Supinic/supinic.com/blob/master/routes/track/detail.js#L27), add formatted video title name into the page's title for easier bookmarking and overall navigation.

The title is inserted into any endpoint's header in the [header.pug](https://github.com/Supinic/supinic.com/blob/master/views/header.pug#L2) view. You can easily add title by passing the `title` property into a render call.

**Comment by 2802harsh** [comment]
Please assign this issue to me

**Comment by 2802harsh** [comment]
Hey @Supinic, while setting up the project, I am getting some error :
![Screenshot from 2020-10-18 23-06-06](https://user-images.githubusercontent.com/58396239/96375420-8c354500-1196-11eb-99d7-bf1fb6b79a38.png)

**Comment by Supinic** [comment]
@2802harsh You're running the project without node support for the `optional chaining` operator. your node must be at least `13.0+` with the `--optional-chaining-operator` runtime param, or `14.0+` without.

Also please note that the project really isn't designed to be cloned/forked, so you might run into more issues.
